# Generated by Django 3.1.12 on 2025-05-25 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietaryPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_types', models.JSONField(blank=True, default=list, null=True)),
                ('preferred_flavors', models.JSONField(blank=True, default=list, null=True)),
                ('price_range', models.CharField(blank=True, max_length=10, null=True)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_preferences', to='user_management.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styles', models.JSONField(blank=True, default=list, null=True)),
                ('preferred_colors', models.JSONField(blank=True, default=list, null=True)),
                ('preferred_brands', models.JSONField(blank=True, default=list, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_preferences', to='user_management.userprofile')),
            ],
        ),
    ]
